#pragma once

#include "types/PlayerEntry.h"
#include <mc/world/actor/player/Player.h>
#include <optional>
#include <future>
#include <functional>

#ifndef PLAYERDB_API
#ifdef PLAYERDB_EXPORT
#define PLAYERDB_API __declspec(dllexport)
#else
#define PLAYERDB_API __declspec(dllimport)
#endif
#endif

extern "C++" {

namespace player_db::api {

// clang-format off
/**
 * @brief Adds a new player entry or updates an existing one in the database using the player's current data.
 * @param player The active player object.
 * @return The updated or newly created PlayerEntry.
 */
PLAYERDB_API types::PlayerEntry addOrUpdatePlayerEntry(const Player& player);

/**
 * @brief Adds a player entry with only name and/or XUID. Used when full player information is not available.
 * @param name The real name of the player (optional).
 * @param xuid The XUID of the player (optional).
 * @return The newly created PlayerEntry.
 */
PLAYERDB_API types::PlayerEntry addUnknownPlayerEntry(const std::string& name = "", const std::string& xuid = "");

/**
 * @brief Gets a player's entry from the database using the active player object.
 * @param player The active player object.
 * @return The PlayerEntry associated with the player.
 * @throws std::runtime_error if the entry is not found.
 */
PLAYERDB_API types::PlayerEntry getPlayerEntry(const Player& player);

/**
 * @brief Gets a player's entry from the database using the PlayerDB-generated UUID.
 * @param uuid The unique UUID generated by PlayerDB for the user.
 * @return An optional containing the PlayerEntry if found, std::nullopt otherwise.
 */
PLAYERDB_API std::optional<types::PlayerEntry> getPlayerEntry(const mce::UUID& uuid);

/**
 * @brief Gets a player's entry from the database by name and/or XUID.
 * @param name The real name of the player (optional).
 * @param xuid The XUID of the player (optional).
 * @return An optional containing the PlayerEntry if found, std::nullopt otherwise.
 */
PLAYERDB_API std::optional<types::PlayerEntry> getPlayerEntry(const std::string& name = "", const std::string& xuid = "");
// clang-format on

/**
 * @brief Gets a player's entry from the database by their real name.
 * @param name The real name of the player.
 * @return An optional containing the PlayerEntry if found, std::nullopt otherwise.
 */
PLAYERDB_API std::optional<types::PlayerEntry> getPlayerEntryByName(const std::string& name);

/**
 * @brief Gets a player's entry from the database by their XUID.
 * @param xuid The XUID of the player.
 * @return An optional containing the PlayerEntry if found, std::nullopt otherwise.
 */
PLAYERDB_API std::optional<types::PlayerEntry> getPlayerEntryByXuid(const std::string& xuid);

/**
 * @brief Gets a player's entry from the database by their Minecraft/Xbox Live UUID.
 * @param uuid The Minecraft client UUID of the player.
 * @return An optional containing the PlayerEntry if found, std::nullopt otherwise.
 */
PLAYERDB_API std::optional<types::PlayerEntry> getEntryByMinecraftUUID(const mce::UUID& uuid);

/**
 * @brief Gets a list of players with similar connection attributes (IP, CID, device ID, device model, self-signed ID, playfab ID).
 * @param player The active player to compare against.
 * @return A vector of similar PlayerEntries.
 */
PLAYERDB_API std::vector<types::PlayerEntry> getSimilarEntries(const Player& player);

/**
 * @brief Queries the users table in the database synchronously.
 * @param sqlQuery A full SQL query or a WHERE clause condition.
 * @return A vector of PlayerEntries matching the query.
 */
PLAYERDB_API std::vector<types::PlayerEntry> queryPlayerEntries(const std::string& sqlQuery);

/**
 * @brief Queries the database asynchronously.
 * @param sqlQuery A full SQL query or a WHERE clause condition.
 * @return A future containing the vector of matched PlayerEntries.
 */
PLAYERDB_API std::future<std::vector<types::PlayerEntry>> queryPlayerEntriesAsync(const std::string& sqlQuery);

/**
 * @brief Queries the database asynchronously, calling the provided callback on completion.
 * @param sqlQuery A full SQL query or a WHERE clause condition.
 * @param callback Callback function executed with the result on the main server thread.
 */
PLAYERDB_API void queryPlayerEntriesAsync(
    const std::string&                                               sqlQuery,
    std::function<void(std::vector<types::PlayerEntry>)>             callback
);

} // namespace player_db::api
}